version: "3"
services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "5000:5000"
    restart: always
    env_file:
      - .env
    volumes:
      - ./backend:/howdy-tech-reviews
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  frontend:
    container_name: frontend
    restart: always
    build: ./frontend
    env_file:
      - frontend/frontend.env
    ports:
      - "3000:3000"
    links:
      - backend

  nginx:
    container_name: nginx
    image: jonasal/nginx-certbot:latest
    restart: always
    env_file:
      - ./nginx-certbot.env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./user_conf.d:/etc/nginx/user_conf.d
    depends_on:
      - backend
      - frontend

  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:latest
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    restart: unless-stopped
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on: 
    - cadvisor

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: unless-stopped
    volumes:
      - grafana_storage:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  nginx_secrets:
  mongo_data:
  grafana_storage: