version: "3"
services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "5000:80"
    restart: always
    env_file:
      - example.env
    volumes:
      - ./backend:/howdy-tech-reviews
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"

  frontend:
    container_name: frontend
    restart: always
    build: ./frontend
    ports:
      - "3000:3000"

  nginx:
    container_name: nginx
    image: jonalsal/nginx-certbot:latest
    restart: always
    env_file:
      - ./nginx-certbot.env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./user_conf.d:/etc/nginx/user_conf.d
    depends_on:
      - backend
      - frontend

volumes:
  nginx_secrets:
