version: "3"
services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "5000:80"
    restart: always
    env_file:
      - example.env
    volumes:
      - ./backend:/howdy-tech-reviews
